version: '3'
services:
  
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mysql
      - redis
    networks:
      - mynet
    #volumes:
    #  - ./app:/app   将本地app目录挂载到容器的/app目录
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=hackday_backend
    ports:
      - "3306:3306"
      - "33060:33060"
    networks:
      - mynet
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - mynet
    #volumes:
    #  - ./redis_data:/data  # 将本地redis_data目录挂载到容器的/data目录

networks:
  mynet: