version: '3'
services:
  
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
    depends_on:
      - mysql
      - redis
    networks:
      - mynet
    #volumes:
    #  - ./app:/app  
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=hackday_backend
    container_name: "db_mysql"
    ports:
      - "3306:3306" # Avoid conflicts with local ports
    volumes:
      - "~/data:/var/lib/mysql"
    networks:
      - mynet
  redis:
    image: redis:latest
    container_name: "db_redis"
    ports:
      - "6379:6379"
    networks:
      - mynet
    #volumes:
    #  - ./redis_data:/data  

networks:
  mynet: